In [2]:
#importing the necessary libraries
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
import seaborn as sb
import scipy.cluster.hierarchy as sch
from sklearn.cluster import AgglomerativeClustering

In [3]:
crime=pd.read_csv("crime_data.csv")
crime

        Unnamed: 0  Murder  Assault  UrbanPop  Rape
0          Alabama    13.2      236        58  21.2
1           Alaska    10.0      263        48  44.5
2          Arizona     8.1      294        80  31.0
3         Arkansas     8.8      190        50  19.5
4       California     9.0      276        91  40.6
5         Colorado     7.9      204        78  38.7
6      Connecticut     3.3      110        77  11.1
7         Delaware     5.9      238        72  15.8
8          Florida    15.4      335        80  31.9
9          Georgia    17.4      211        60  25.8
10          Hawaii     5.3       46        83  20.2
11           Idaho     2.6      120        54  14.2
12        Illinois    10.4      249        83  24.0
13         Indiana     7.2      113        65  21.0
14            Iowa     2.2       56        57  11.3
15          Kansas     6.0      115        66  18.0
16        Kentucky     9.7      109        52  16.3
17       Louisiana    15.4      249        66  22.2
18           Maine     2.1       83        51   7.8
19        Maryland    11.3      300        67  27.8
20   Massachusetts     4.4      149        85  16.3
21        Michigan    12.1      255        74  35.1
22       Minnesota     2.7       72        66  14.9
23     Mississippi    16.1      259        44  17.1
24        Missouri     9.0      178        70  28.2
25         Montana     6.0      109        53  16.4
26        Nebraska     4.3      102        62  16.5
27          Nevada    12.2      252        81  46.0
28   New Hampshire     2.1       57        56   9.5
29      New Jersey     7.4      159        89  18.8
30      New Mexico    11.4      285        70  32.1
31        New York    11.1      254        86  26.1
32  North Carolina    13.0      337        45  16.1
33    North Dakota     0.8       45        44   7.3
34            Ohio     7.3      120        75  21.4
35        Oklahoma     6.6      151        68  20.0
36          Oregon     4.9      159        67  29.3
37    Pennsylvania     6.3      106        72  14.9
38    Rhode Island     3.4      174        87   8.3
39  South Carolina    14.4      279        48  22.5
40    South Dakota     3.8       86        45  12.8
41       Tennessee    13.2      188        59  26.9
42           Texas    12.7      201        80  25.5
43            Utah     3.2      120        80  22.9
44         Vermont     2.2       48        32  11.2
45        Virginia     8.5      156        63  20.7
46      Washington     4.0      145        73  26.2
47   West Virginia     5.7       81        39   9.3
48       Wisconsin     2.6       53        66  10.8
49         Wyoming     6.8      161        60  15.6

In [4]:
#normalizatin function min max
def norm_func(i):
    x=(i-i.min())/(i-i.max()-(i-i.min()))
    return (x)

In [5]:
crime_norm=norm_func(crime.iloc[:,1:])
crime_norm

      Murder   Assault  UrbanPop      Rape
0  -0.746988 -0.654110 -0.440678 -0.359173
1  -0.554217 -0.746575 -0.271186 -0.961240
2  -0.439759 -0.852740 -0.813559 -0.612403
3  -0.481928 -0.496575 -0.305085 -0.315245
4  -0.493976 -0.791096 -1.000000 -0.860465
5  -0.427711 -0.544521 -0.779661 -0.811370
6  -0.150602 -0.222603 -0.762712 -0.098191
7  -0.307229 -0.660959 -0.677966 -0.219638
8  -0.879518 -0.993151 -0.813559 -0.635659
9  -1.000000 -0.568493 -0.474576 -0.478036
10 -0.271084 -0.003425 -0.864407 -0.333333
11 -0.108434 -0.256849 -0.372881 -0.178295
12 -0.578313 -0.698630 -0.864407 -0.431525
13 -0.385542 -0.232877 -0.559322 -0.354005
14 -0.084337 -0.037671 -0.423729 -0.103359
15 -0.313253 -0.239726 -0.576271 -0.276486
16 -0.536145 -0.219178 -0.338983 -0.232558
17 -0.879518 -0.698630 -0.576271 -0.385013
18 -0.078313 -0.130137 -0.322034 -0.012920
19 -0.632530 -0.873288 -0.593220 -0.529716
20 -0.216867 -0.356164 -0.898305 -0.232558
21 -0.680723 -0.719178 -0.711864 -0.718346
22 -0.114458 -0.092466 -0.576271 -0.196382
23 -0.921687 -0.732877 -0.203390 -0.253230
24 -0.493976 -0.455479 -0.644068 -0.540052
25 -0.313253 -0.219178 -0.355932 -0.235142
26 -0.210843 -0.195205 -0.508475 -0.237726
27 -0.686747 -0.708904 -0.830508 -1.000000
28 -0.078313 -0.041096 -0.406780 -0.056848
29 -0.397590 -0.390411 -0.966102 -0.297158
30 -0.638554 -0.821918 -0.644068 -0.640827
31 -0.620482 -0.715753 -0.915254 -0.485788
32 -0.734940 -1.000000 -0.220339 -0.227390
33 -0.000000 -0.000000 -0.203390 -0.000000
34 -0.391566 -0.256849 -0.728814 -0.364341
35 -0.349398 -0.363014 -0.610169 -0.328165
36 -0.246988 -0.390411 -0.593220 -0.568475
37 -0.331325 -0.208904 -0.677966 -0.196382
38 -0.156627 -0.441781 -0.932203 -0.025840
39 -0.819277 -0.801370 -0.271186 -0.392765
40 -0.180723 -0.140411 -0.220339 -0.142119
41 -0.746988 -0.489726 -0.457627 -0.506460
42 -0.716867 -0.534247 -0.813559 -0.470284
43 -0.144578 -0.256849 -0.813559 -0.403101
44 -0.084337 -0.010274 -0.000000 -0.100775
45 -0.463855 -0.380137 -0.525424 -0.346253
46 -0.192771 -0.342466 -0.694915 -0.488372
47 -0.295181 -0.123288 -0.118644 -0.051680
48 -0.108434 -0.027397 -0.576271 -0.090439
49 -0.361446 -0.397260 -0.474576 -0.214470

In [6]:
#creating cluster
crime_c = AgglomerativeClustering(n_clusters=4,affinity='euclidean', linkage='single')
crime_c

AgglomerativeClustering(linkage='single', n_clusters=4)

In [7]:
#save clusters for chart
crime_nc = crime_c.fit_predict(crime_norm)
crime_nc

array([0, 3, 0, 0, 0, 0, 0, 1, 2, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0], dtype=int64)

In [8]:
Clusters=pd.DataFrame(crime_nc,columns=['Cluster_hi'])
Clusters

    Cluster_hi
0            0
1            3
2            0
3            0
4            0
5            0
6            0
7            1
8            2
9            0
10           0
11           0
12           0
13           0
14           0
15           0
16           0
17           0
18           0
19           0
20           0
21           0
22           0
23           0
24           0
25           0
26           0
27           0
28           0
29           0
30           0
31           0
32           0
33           0
34           0
35           0
36           0
37           0
38           0
39           0
40           0
41           0
42           0
43           0
44           0
45           0
46           0
47           0
48           0
49           0

In [9]:
crime['clusterid_hi'] = crime_c.labels_

In [10]:
crime

        Unnamed: 0  Murder  Assault  UrbanPop  Rape  clusterid_hi
0          Alabama    13.2      236        58  21.2             0
1           Alaska    10.0      263        48  44.5             3
2          Arizona     8.1      294        80  31.0             0
3         Arkansas     8.8      190        50  19.5             0
4       California     9.0      276        91  40.6             0
5         Colorado     7.9      204        78  38.7             0
6      Connecticut     3.3      110        77  11.1             0
7         Delaware     5.9      238        72  15.8             1
8          Florida    15.4      335        80  31.9             2
9          Georgia    17.4      211        60  25.8             0
10          Hawaii     5.3       46        83  20.2             0
11           Idaho     2.6      120        54  14.2             0
12        Illinois    10.4      249        83  24.0             0
13         Indiana     7.2      113        65  21.0             0
14            Iowa     2.2       56        57  11.3             0
15          Kansas     6.0      115        66  18.0             0
16        Kentucky     9.7      109        52  16.3             0
17       Louisiana    15.4      249        66  22.2             0
18           Maine     2.1       83        51   7.8             0
19        Maryland    11.3      300        67  27.8             0
20   Massachusetts     4.4      149        85  16.3             0
21        Michigan    12.1      255        74  35.1             0
22       Minnesota     2.7       72        66  14.9             0
23     Mississippi    16.1      259        44  17.1             0
24        Missouri     9.0      178        70  28.2             0
25         Montana     6.0      109        53  16.4             0
26        Nebraska     4.3      102        62  16.5             0
27          Nevada    12.2      252        81  46.0             0
28   New Hampshire     2.1       57        56   9.5             0
29      New Jersey     7.4      159        89  18.8             0
30      New Mexico    11.4      285        70  32.1             0
31        New York    11.1      254        86  26.1             0
32  North Carolina    13.0      337        45  16.1             0
33    North Dakota     0.8       45        44   7.3             0
34            Ohio     7.3      120        75  21.4             0
35        Oklahoma     6.6      151        68  20.0             0
36          Oregon     4.9      159        67  29.3             0
37    Pennsylvania     6.3      106        72  14.9             0
38    Rhode Island     3.4      174        87   8.3             0
39  South Carolina    14.4      279        48  22.5             0
40    South Dakota     3.8       86        45  12.8             0
41       Tennessee    13.2      188        59  26.9             0
42           Texas    12.7      201        80  25.5             0
43            Utah     3.2      120        80  22.9             0
44         Vermont     2.2       48        32  11.2             0
45        Virginia     8.5      156        63  20.7             0
46      Washington     4.0      145        73  26.2             0
47   West Virginia     5.7       81        39   9.3             0
48       Wisconsin     2.6       53        66  10.8             0
49         Wyoming     6.8      161        60  15.6             0